### ISSUE TITLE
Mid-Project Peer Code Review Request

### ISSUE THREAD

**Issue by jorgieo** [jorgieo/eventuallyApp#28]
Please take a second to review the application. This is an Ionic/Angular app that uses Google's Firebase as the backend for authentication and data storage.

Use this link to test the UI:

https://eventuallyapp-5523e--ui-test-94azo37h.web.app

This is the way I have implemented user login:
https://github.com/jorgieo/eventuallyApp/blob/e4584c7a483b5bd8f66a32ec858c2b714c00b191/eventually/src/app/login/login.page.ts#L24-L45

To register a user, as for every other part of the authentication workflow, I am leveraging the angular/fire API. Here is the user registration:
https://github.com/jorgieo/eventuallyApp/blob/e4584c7a483b5bd8f66a32ec858c2b714c00b191/eventually/src/app/register/register.page.ts#L25-L48

The majority of the interactions will stem from the /home page. Here is how I am retrieving event objects:
https://github.com/jorgieo/eventuallyApp/blob/e4584c7a483b5bd8f66a32ec858c2b714c00b191/eventually/src/app/home/home.page.ts#L31-L49

One of the parts I have done a lot of re-work on has been the routes. Take a look at what I have so far and let me know if you see any issues. Mind you, I have not yet implemented front-end routing guards, but this is being tracked on the project board.
https://github.com/jorgieo/eventuallyApp/blob/e4584c7a483b5bd8f66a32ec858c2b714c00b191/eventually/src/app/app-routing.module.ts#L4-L38

Also, take a look at the GitHub project for a glimpse into what has been done so far and planned tasks:
https://github.com/jorgieo/eventuallyApp/projects/1

**Comment by code987-bio** [comment]
Hey Jorge,

Your routes look fine!  I would focus on adding a method to get back to the event after the user is at the guest list.  There seems to be a way there, but not a way to reverse the location.  Maybe you can create a link inside the page that takes the user back to the event page they just created.  What happens if a person wants to edit the page they were on once they reach the list page?  So, you see there should be a way to get back to that page where edits can be made.  Say for instance, if a person wants to edit the event or the time, do they currently have a way to do that from the list page?  That is the only question I'm asking.  Maybe there is a way that I didn't see it.  Please point it out to me!

**Comment by jorgieo** [comment]
@code987-bio  Thanks for the feedback!

I agree the navigation workflow is a bit broken, but it's a work-in-progress. What I will implement is a back button from the guest list toolbar that routes back to the event. Much like the one in the event details page toolbar.
